CREATE OR REPLACE PROCEDURE FAKE_STORE.GOLD.GET_CUSTOMER_TOTAL_SPEND_REPORT()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    INSERT OVERWRITE INTO FAKE_STORE.GOLD.CUSTOMER_TOTAL_SPEND_REPORT
    SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, SUM(O.QUANTITY * P.PRICE) AS TOTAL_SPENDIG
    FROM FAKE_STORE.SILVER.DIM_USERS U
    LEFT JOIN FAKE_STORE.SILVER.FACT_ORDERS O
        ON U.USER_ID = O.USER_ID
    LEFT JOIN FAKE_STORE.SILVER.DIM_PRODUCTS P
        ON O.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY ALL
    ORDER BY 1;

    COMMIT;
    
    RETURN 'SUCCESS';

END;
$$;