CREATE OR REPLACE TABLE FAKE_STORE.SILVER.DIM_USERS(
    USER_ID NUMBER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    ADDRESS VARCHAR,
    CITY VARCHAR,
    ZIP VARCHAR, 
    ZIP_PLUS_FOUR VARCHAR,
    LATITUDE VARCHAR,
    LONGITUDE VARCHAR
);