CREATE OR REPLACE TABLE FAKE_STORE.SILVER.DIM_PRODUCTS(
    PRODUCT_ID NUMBER(10,0),
    PRODUCT_NAME VARCHAR,
    DESCRIPTION VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2),
    NUMBER_OF_RATINGS NUMBER(10,0),
    RATING NUMBER(10,2)
);